version: "3.7"
services:
    
  currency_mysql:
    image: mysql:8.0.17
    container_name: currency_mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - 'currency_mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: userpassword
      MYSQL_DATABASE: currency
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '53306:3306'
    networks:
      - currency_backend
      
networks:
  currency_backend:
volumes:
    currency_mysql_data:
